export const PATHS = {
  HOME: "/",
  QUOTE: "/cotizar",
  COMPARE: "/comparar",
  BLOG: "/blog",
  STORES: "/tiendas",
  ABOUT: "/nosotros",
  CONTACT: "/contacto",
  PRODUCTS: "/productos",
  ACCOUNT: "/cuenta",
  accountOrders: '/cuenta/pedidos',
  accountAddress: '/cuenta/direccion',
  accountFavorites: '/cuenta/favoritos',
  accountHelp: '/cuenta/ayuda',
} as const;
